# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrelcacti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
