# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrelcacti', '0003_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='source',
        ),
    ]
