# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('barrelcacti', '0006_auto_20160813_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
